name: Build and Package Executable (Rust)

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable  # You can specify a version if you need a specific one

      - name: Install dependencies for Ubuntu or macOS
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            # Install necessary dependencies on Ubuntu
            sudo apt-get update
            sudo apt-get install -y build-essential
            # Install any other dependencies your project requires here
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            # Install necessary dependencies on macOS
            brew install llvm
            # Install any other dependencies your project requires here
          fi

      - name: Build the project with Cargo
        run: |
          cargo build --release  # Build the project for release

      - name: Package the executable
        run: |
          mkdir -p release/${{ matrix.os }}
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            # Move the executable for Ubuntu
            mv target/release/my_project release/ubuntu-latest/my_project
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            # Move the executable for macOS
            mv target/release/my_project release/macos-latest/my_project
          fi

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/ubuntu-latest/my_project
            release/macos-latest/my_project
