name: Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest


    steps:
    - uses: actions/checkout@v4
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: aarch64-apple-darwin

    - name: Build
      run: cargo build --release --target ${{ matrix.target }}

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: aarch64-apple-darwin-build
        path: target/aarch64-apple-darwin/release

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        path: ./build
        name: aarch64-apple-darwin-build

    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        files: ./build/*
